name: Avoid Rate Limit
description: Pause workflow to avoid hitting the rate limit
inputs:
  sleep_time:
    description: Duration in seconds to sleep
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.sleep_time }}" -eq 0 ]]; then
          echo "Skip Pause ... Far from Rate Limit"
        else
          echo "${{ inputs.sleep_time }} Second Pause for Rate Limit"
          sleep ${{ inputs.sleep_time }}
        fi
      shell: bash
