name: Build Artefacts

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Required Build Type(s)'
        type: choice
        options:
        - 'REL Only'
        - 'DBG Only'
        - 'NPT Only'
        - 'REL and DBG'
        - 'REL, DBG, NPT'
        default: 'REL and DBG'
      sign_output:
        description: 'Sign Binaries for Secure Boot?'
        type: choice
        options:
        - 'NO'
        - 'YES'
        default: 'NO'
      commit_id:
        description: 'Commit ID (Blank == GOPFix-Latest)'
        type: string
        required: false

jobs:
  make-binaries:
    name: Make Binaries
    runs-on: macos-latest

    steps:
      - name: List/Set Misc
        env:
          SET_REPO: ${{ github.repository }}
          SET_COMMIT_ID: ${{ github.event.inputs.commit_id }}
          SET_BUILD_TYPE: ${{ github.event.inputs.build_type }}
          SET_SIGN_OUTPUT: ${{ github.event.inputs.sign_output }}
        shell: bash
        run: |
          # List Misc Inputs
          echo "REPO       : '${SET_REPO}'"
          echo "ENV_REPO=${SET_REPO}" >> "${GITHUB_ENV}"

          USE_COMMIT_ID="${SET_COMMIT_ID:-GOPFix-Latest}"
          echo "COMMIT_ID  : '${USE_COMMIT_ID}'"
          echo "ENV_COMMIT_ID=${USE_COMMIT_ID}" >> "${GITHUB_ENV}"

          echo "BUILD_FLAG : '${SET_BUILD_TYPE}'"
          echo "ENV_BUILD_TYPE=${SET_BUILD_TYPE}" >> "${GITHUB_ENV}"

          echo "SECURE_BOOT: '${SET_SIGN_OUTPUT}'"

          # Set Misc Paths
          USE_BASE="${HOME}/Documents/RefindPlus"
          echo "ENV_BASE_DIR=${USE_BASE}" >> "${GITHUB_ENV}"
          echo "ENV_EDK2_DIR=${USE_BASE}/edk2" >> "${GITHUB_ENV}"
          echo "ENV_WORK_DIR=${USE_BASE}/Working" >> "${GITHUB_ENV}"

      - name: Get Repositories
        shell: bash
        run: |
          # Create Directories
          mkdir -p "${ENV_BASE_DIR}" || exit 1
          cd "${ENV_BASE_DIR}" || exit 1

          # Clone Repos
          git clone "https://github.com/${ENV_REPO}.git" Working || exit 1
          git clone "https://github.com/RefindPlusRepo/RefindPlusUDK.git" edk2 || exit 1

      - name: Determine Target Branch
        shell: bash
        run: |
          # Set Target Branch/Commit
          cd "${ENV_WORK_DIR}" || exit 1
          if [[ "${ENV_COMMIT_ID}" == 'GOPFix-Latest' ]] ; then
            echo "Blank Commit ID Input ... Use Defaults"
            BRANCH=GOPFix
          else
            echo "Find User Defined Branch via Commit ID"
            # Validate Input 'Commit ID'
            if [[ ! "${ENV_COMMIT_ID}" =~ ^[a-fA-F0-9]{7,40}$ ]]; then
              echo "Error: Invalid Commit ID Format: '${ENV_COMMIT_ID}'"
              echo "       Must be Valid Git SHA (7-40 Hex Chars)"
              echo "       Exiting Now"
              exit 1
            fi

            # Fetch valid remote branches
            git fetch origin --prune

            # Get Candidate Branches
            BranchList=$(git branch -r --contains "${ENV_COMMIT_ID}" | grep 'origin/' | sed 's|origin/||')
            if [[ -z "${BranchList}" ]]; then
              echo "Error: Not Located on Any Branch: '${ENV_COMMIT_ID}'"
              echo "       Exiting Now"
              exit 1
            fi

            # Use Target Branch Commit
            BRANCH=$(printf "%s\n" "${BranchList}" | head -n 1 | tr -d '[:space:]')
            if ! git show-ref --verify --quiet "refs/remotes/origin/${BRANCH}"; then
              echo "Error: Remote Branch Not Found: '${BRANCH}'"
              echo "       Paranoia Check Failed!"
              echo "       Exiting Now"
              exit 1
            fi

            # Set Target Branch to Commit ID
            git checkout "${BRANCH}"
            git reset --hard "${ENV_COMMIT_ID}"
          fi

          echo "BRANCH=${BRANCH}" >> "${GITHUB_ENV}"
          echo "Branch     : '${BRANCH}'"

          printf "Commit     : '%s'\nTitle      : '%s'\n" \
            "$(git rev-parse --short HEAD)" \
            "$(git log -1 --pretty=%B | sed 's/%/%%/g')"

          printf "Author     : '%s'\nDate       : '%s'\n" \
            "$(git log -1 --pretty='%an <%ae>')" \
            "$(git log -1 --pretty='%ad' --date=iso-strict)"

      - name: Apply Misc Prep
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        shell: bash
        run: |
          # Set Build Type(s)
          case "${ENV_BUILD_TYPE}" in
            "REL and DBG") BUILD_FLAG="TWO" ;;
            "REL Only")    BUILD_FLAG="REL" ;;
            "DBG Only")    BUILD_FLAG="DBG" ;;
            "NPT Only")    BUILD_FLAG="NPT" ;;
            *)             BUILD_FLAG="ALL" ;;
          esac

          echo "BUILD_FLAG=${BUILD_FLAG}" >> "${GITHUB_ENV}"
          echo "Build Type : '${BUILD_FLAG}'"

          # Set Type Flag
          FlagFind=0
          ADD_TAG="${ENV_WORK_DIR}/Main/main.c"
          if [[ -f "${ADD_TAG}" ]]; then
            FlagFind=1
          else
            ADD_TAG="${ENV_WORK_DIR}/BootMaster/main.c"
            if [[ -f "${ADD_TAG}" ]]; then
              FlagFind=1
            fi
          fi

          if (( FlagFind )) ; then
            /usr/bin/perl -i -p -e 's~\(Local\)~(Outer)~' "${ADD_TAG}" || {
              echo "[NOTE] Tag Replacement Failed: '${ADD_TAG}'"
            }
          fi

          # Install Additional Build Tools
          PKGS="nasm acpica ocmtoc"
          brew install ${PKGS} || (
            brew update && brew install ${PKGS}
          )

          # Install Final Python 2 Version
          PYTHON_VER='2.7.18'
          PYTHON_PKG="python-${PYTHON_VER}-macosx10.9.pkg"
          EXPECT_MD5='ce98eeb7bdf806685adc265ec1444463'

          PYTHON2_INSTALLER="${ENV_EDK2_DIR}/Conf/Blobs/${PYTHON_PKG}"
          if [[ -f "${PYTHON2_INSTALLER}" ]]; then
            cp -f "${PYTHON2_INSTALLER}" . || true
          fi

          if [[ -f "${PYTHON_PKG}" ]]; then
            printf "\nUsing Bundled Python %s\n" "${PYTHON_VER}"
            printf "Verify Python %s File\n" "${PYTHON_VER}"
            ACTUAL_MD5=$(md5 -q "${PYTHON_PKG}")
            if [[ "${ACTUAL_MD5}" != "${EXPECT_MD5}" ]]; then
              echo "ERROR: Python Bundle Checksum Check Failure"
              echo "       Expect: ${EXPECT_MD5}"
              echo "       Actual: ${ACTUAL_MD5}"

              rm -f "${PYTHON_PKG}"
              printf "\n\nFetch From Project Page Instead"
            fi
          fi

          if [[ ! -f "${PYTHON_PKG}" ]]; then
            PYTHON_URL="https://www.python.org/ftp/python/${PYTHON_VER}/${PYTHON_PKG}"
            printf "\nDownloading Python %s\n" "${PYTHON_VER}"
            curl --retry 3 --fail -O "${PYTHON_URL}" || {
              printf "\nERROR: Python %s Download Failed\n" "${PYTHON_VER}"
              exit 1
            }

            printf "Verify Python %s Download\n" "${PYTHON_VER}"
            ACTUAL_MD5=$(md5 -q "${PYTHON_PKG}")
            if [[ "${ACTUAL_MD5}" != "${EXPECT_MD5}" ]]; then
              echo "ERROR: Python Download Checksum Check Failure"
              echo "       Expect: ${EXPECT_MD5}"
              echo "       Actual: ${ACTUAL_MD5}"
              echo "       Exiting Now"
              exit 1
            fi
          fi

          printf "Verified ... Installing Python %s\n" "${PYTHON_VER}"
          sudo installer -pkg "${PYTHON_PKG}" -target /

      - name: Run Main Script
        env:
          TERM: xterm
        shell: bash
        run: |
          # Main Build Script
          cd "${ENV_BASE_DIR}/edk2/000-BuildScript" || exit 1
          chmod +x RefindPlusBuilder.sh
          ./RefindPlusBuilder.sh "${BRANCH}" "${BUILD_FLAG}"


        ###
        # If signing is active, prefix with 'NOT_SIGNED---' for the
        # signing job to handle the final outputs without collision
        ###
      - name: Upload Artefact (REL)
        if: success() && contains(github.event.inputs.build_type, 'REL')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_REL' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_REL' }}"
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/RELEASE_XCODE5/x64/*.efi

      - name: Upload Artefact (DBG)
        if: success() && contains(github.event.inputs.build_type, 'DBG')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_DBG' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_DBG' }}"
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/DEBUG_XCODE5/x64/*.efi

      - name: Upload Artefact (NPT)
        if: success() && contains(github.event.inputs.build_type, 'NPT')
        uses: actions/upload-artifact@v6
        with:
          name: "${{ github.event.inputs.sign_output == 'NO' && 'x64_RefindPlus-Artefacts_NPT' || 'NOT_SIGNED---x64_RefindPlus-Artefacts_NPT' }}"
          path: ~/Documents/RefindPlus/edk2/Build/RefindPlus/NOOPT_XCODE5/x64/*.efi

  sign-binaries:
    name: Sign Binaries
    needs: make-binaries
    if: ${{ github.event.inputs.sign_output == 'YES' }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate Repository Secrets
        shell: bash
        env:
          INPUT_KEY: ${{ secrets.SIG_RP_KEY }}
          INPUT_CRT: ${{ secrets.SIG_RP_CRT }}
          INPUT_CER: ${{ secrets.SIG_RP_CER }}
        run: |
          # Vet Repository Secrets Setup (If Detected)
          [[ -z "${INPUT_KEY}" && (-n "${INPUT_CRT}" || -n "${INPUT_CER}") ]] && NO_KEY=1 || NO_KEY=0
          [[ -n "${INPUT_KEY}" &&  -z "${INPUT_CRT}" ]]                       && NO_CRT=1 || NO_CRT=0
          [[ -n "${INPUT_CER}" &&  -z "${INPUT_CRT}" && "${NO_CRT}" == "0" ]] && NO_CRT=1 || true

          if (( NO_KEY || NO_CRT )); then
            echo "ERROR: Invalid Repository Secrets Setup for Secure Boot Signing"

            (( NO_KEY )) && echo "       The required 'SIG_RP_KEY' repository secret is missing"
            (( NO_CRT )) && echo "       The required 'SIG_RP_CRT' repository secret is missing"

            echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
            echo "       Exiting Now"
            exit 1
          fi

      - name: Fetch Interim Artefact (REL)
        if: contains(github.event.inputs.build_type, 'REL')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_REL
          path: Unsigned_REL

      - name: Fetch Interim Artefact (DBG)
        if: contains(github.event.inputs.build_type, 'DBG')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_DBG
          path: Unsigned_DBG

      - name: Fetch Interim Artefact (NPT)
        if: contains(github.event.inputs.build_type, 'NPT')
        uses: actions/download-artifact@v7
        with:
          name: NOT_SIGNED---x64_RefindPlus-Artefacts_NPT
          path: Unsigned_NPT

      - name: Prepare to Sign Binaries
        shell: bash
        env:
          ENV_USER_KEY: ${{ secrets.SIG_RP_KEY }}
          ENV_USER_CRT: ${{ secrets.SIG_RP_CRT }}
          ENV_USER_CER: ${{ secrets.SIG_RP_CER }}
        run: |
          # Handle Certificate and Private Key
          Certs="Artefact_Certs"
          mkdir -p "${Certs}"
          NOW=$(date +%y%m%d%H%M%S)
          CERT_PATH="${Certs}/build_cert_${NOW}"

          if [[ -n "${ENV_USER_KEY}" ]]; then
            echo "Cert/Key: Fetch User-Provided"
            echo "${ENV_USER_KEY}" > "${CERT_PATH}.key"

            if [[ -n "${ENV_USER_CRT}" ]]; then
              echo "${ENV_USER_CRT}" > "${CERT_PATH}.crt"
            fi
            if [[ -n "${ENV_USER_CER}" ]]; then
              echo "${ENV_USER_CER}" > "${CERT_PATH}.cer"
            fi
          fi

          if [[ -z "${ENV_USER_CRT}" ]]; then
            ENV_USER_KEY="${CERT_PATH}.key"
            ENV_USER_CRT="${CERT_PATH}.crt"
            ENV_USER_CER="${CERT_PATH}.cer"

            echo "Cert/Key: Generate Transient"
            openssl req -new -x509 -nodes \
              -newkey rsa:2048 \
              -keyout "${ENV_USER_KEY}" \
              -out "${ENV_USER_CRT}" \
              -days 3650 \
              -subj "/CN=RefindPlus Build Artefact ${NOW}/"
          fi

          if [[ (-z "${ENV_USER_CER}" || ! -f "${ENV_USER_CER}")  && -f "${ENV_USER_CRT}" ]]; then
            # Create '.cer' From '.crt' For UEFI Enrolment
            openssl x509 \
              -in "${ENV_USER_CRT}" \
              -out "${ENV_USER_CER}" \
              -outform DER
          fi

          # Store Outputs for Subsequent Steps
          echo "PATH_KEY=${ENV_USER_KEY}" >> $GITHUB_ENV
          echo "PATH_CRT=${ENV_USER_CRT}" >> $GITHUB_ENV
          echo "PATH_CER=${ENV_USER_CER}" >> $GITHUB_ENV
          echo "FLAG_NOW=${NOW}"          >> $GITHUB_ENV

      - name: Sign Requested Binaries
        env:
          ENV_TYPE: ${{ github.event.inputs.build_type }}
        shell: bash
        run: |
          # Sign Files
          sign_files() {
            local target=$1

            local base=""
            local infile=""
            local outfile=""
            local sign_item=0

            local outdir="${target}_signed_DIR"
            mkdir -p "${outdir}"

            printf "\n\n"
            echo "===== Signing Target: ${target} ====="

            # Sign Main Binary
            echo "Sign Main Binary..."
            prefix="x64_RefindPlus_${target}"
            base="APP_xx_${target}---${prefix}"
            infile="Unsigned_${target}/${base}.efi"
            outfile="${outdir}/SIGNED_${FLAG_NOW}___${base}.efi"

            sign_item=0
            if [[ -f "${infile}" ]]; then
              sign_item=1
            else
              base="UEFI_APP---${prefix}"
              infile="Unsigned_${target}/${base}.efi"
              outfile="${outdir}/SIGNED_${FLAG_NOW}___${base}.efi"

              if [[ -f "${infile}" ]]; then
                sign_item=1
              else
                echo "ERROR: Main Binary Not Found: '${prefix}'"
                echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                echo "       Exiting Now"
                exit 1
              fi
            fi

            if (( sign_item )); then
                echo "[SIGN] '${infile}' >>---> as >>---> '${outfile}'"
                sbsign --key "${PATH_KEY}" \
                       --cert "${PATH_CRT}" \
                       --output "${outfile}" "${infile}" || {
                  echo "ERROR: Failed While Signing ${infile}"
                  echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                  echo "       Exiting Now"
                  exit 1
                }
            fi

            # Sign Misc Tools
            echo ''
            echo "Sign Misc Tools..."
            for prefix in x64_shell x64_memtest86 x64_gptsync x64_gdisk x64_CleanNvram x64_ipxe; do
              base="APP_xx_${target}---${prefix}"
              infile="Unsigned_${target}/${base}.efi"
              outfile="${outdir}/SIGNED_${FLAG_NOW}___${base}.efi"

              sign_item=0
              if [[ -f "${infile}" ]]; then
                sign_item=1
              else
                base="UEFI_APP---${prefix}_${target}"
                infile="Unsigned_${target}/${base}.efi"
                outfile="${outdir}/SIGNED_${FLAG_NOW}___${base}.efi"

                if [[ -f "${infile}" ]]; then
                  sign_item=1
                else
                  echo "[WARN] Not Found: '${infile}' ... SKIPPED"
                fi
              fi

              if (( sign_item )); then
                echo "[SIGN] '${infile}' >>---> as >>---> '${outfile}'"
                sbsign --key "${PATH_KEY}" \
                       --cert "${PATH_CRT}" \
                       --output "${outfile}" "${infile}" || {
                  echo "ERROR: Failed While Signing ${infile}"
                  echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                  echo "       Exiting Now"
                  exit 1
                }
              fi
            done

            # Sign Filesystem Drivers
            echo ''
            echo "Sign Filesystem Drivers..."
            for fs in btrfs ext2 ext4 hfs iso9660 ntfs reiserfs; do
              base="DRIVER_${target}---x64_${fs}"
              infile="Unsigned_${target}/${base}.efi"
              outfile="${outdir}/SIGNED_${FLAG_NOW}_${base}.efi"

              if [[ ! -f "${infile}" ]]; then
                echo "[WARN] Not Found: '${infile}' ... SKIPPED"
              else
                echo "[SIGN] '${infile}' >>--> as >>--> '${outfile}'"
                sbsign --key "${PATH_KEY}" \
                       --cert "${PATH_CRT}" \
                       --output "${outfile}" "${infile}" || {
                  echo "ERROR: Failed While Signing ${infile}"
                  echo "       Unsigned Artefacts Saved with Prefix: 'NOT_SIGNED---'"
                  echo "       Exiting Now"
                  exit 1
                }
              fi
            done

            echo "= = = = Signed Target = = = ="
          }

          # Set Types
          case "${ENV_TYPE}" in
            "REL and DBG") FLAG="TWO" ;;
            "REL Only")    FLAG="REL" ;;
            "DBG Only")    FLAG="DBG" ;;
            "NPT Only")    FLAG="NPT" ;;
            *)             FLAG="ALL" ;;
          esac

          # Sign Binaries
          set +e  # Disable fail-fast
          [[ "${FLAG}" == "REL" || "${FLAG}" == "ALL" || "${FLAG}" == "TWO" ]] && sign_files REL
          [[ "${FLAG}" == "DBG" || "${FLAG}" == "ALL" || "${FLAG}" == "TWO" ]] && sign_files DBG
          [[ "${FLAG}" == "NPT" || "${FLAG}" == "ALL" ]]                       && sign_files NPT
          set -e  # Restore fail-fast

          # Job Final Spacing
          printf "\n\n"


        ###
        # Handle interim artefacts, which are now deleted to leave
        # a final definititve set of artefacts with the same names
        # as produced when signing for secure boot is not required
        ###
      - name: Remove Interim Unsigned Artefacts
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_REPO: ${{ github.repository }}
          ENV_GHID: ${{ github.run_id }}
        shell: bash
        run: |
          echo "Remove Interim Unsigned Artefacts"
          got_artefacts=$(gh api "repos/${ENV_REPO}/actions/runs/${ENV_GHID}/artifacts" \
            --jq '.artifacts[] | select(.name | startswith("NOT_SIGNED---")) | "\(.id):\(.name)"')

          if [[ -z "${got_artefacts}" ]]; then
            echo "Interim Unsigned Artefacts Not Found"
            exit 0
          fi

          FirstPass='True'
          while IFS=":" read -r artifact_id artifact_name; do
            echo "Found: ${artifact_name} (${artifact_id})"
            CleanStrip='True'
            [[ "${FirstPass}" == 'False' ]] && sleep 2
            gh api --method DELETE repos/"${ENV_REPO}"/actions/artifacts/"${artifact_id}" || CleanStrip='False'

            if [[ "${CleanStrip}" == 'True' ]]; then
              echo "Removed Interim Artefact: ${artifact_name} (ID: ${artifact_id})"
              FirstPass='False'
            else
              echo "[WARN] Failed to Remove Interim Artefact: ${artifact_name} (ID: ${artifact_id})"
              FirstPass='True'
            fi
          done <<< "${got_artefacts}"


        ###
        # Always include the certificate files along with the
        # signed binaries for users to enrol for Secure Boot
        ###
      - name: Upload Signed Binaries (REL)
        if: contains(github.event.inputs.build_type, 'REL')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_REL
          path: |
              ${{ env.PATH_CER }}
              ${{ env.PATH_CRT }}
              REL_signed_DIR/*.efi

      - name: Upload Signed Binaries (DBG)
        if: contains(github.event.inputs.build_type, 'DBG')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_DBG
          path: |
              ${{ env.PATH_CER }}
              ${{ env.PATH_CRT }}
              DBG_signed_DIR/*.efi

      - name: Upload Signed Binaries (NPT)
        if: contains(github.event.inputs.build_type, 'NPT')
        uses: actions/upload-artifact@v6
        with:
          name: x64_RefindPlus-Artefacts_NPT
          path: |
              ${{ env.PATH_CER }}
              ${{ env.PATH_CRT }}
              NPT_signed_DIR/*.efi
