name: 'Issue Helper Disavowed Build'

on:
  workflow_dispatch:
    inputs:
      item_id:
        description: 'Item ID'
        type: string
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:
  issue_outdated_version1:
    name: Issue - Outdated - Version1
    runs-on: ubuntu-latest

    steps:
      # Generate App Token - https://github.com/actions/create-github-app-token
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: part_02
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          body: |
            You appear to be running a modified and/or otherwise disavowed build.
            This item is therefore considered invalid and cannot be looked into.

            > [!IMPORTANT]
            > Issues found on modified/customised builds must be tested on official files/code.
            > Should they also appear on these sources, raise your issue based on such sources.
            > Additionally, debug logging and such should be obtained from the offical sources.

            Thank you.

      - id: part_03
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Dropped'

      - id: part_04
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Triage,No-Log,Incomplete,Tagged,Stale,Queries'

      - id: part_05
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          close-reason: 'completed'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}

      - id: part_06
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.inputs.item_id }}

      - id: part_07
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const issueNumber = context.payload.inputs.item_id;
            const { data } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });

      # Set NodeJS Up - https://github.com/actions/setup-node
      - id: part_08
        uses: actions/setup-node@v4
        with:
          # Using range for flexibility
          node-version: '>=20 <22'

      - id: part_09
        env:
          ENV_TOKEN: ${{ steps.app-token.outputs.token }}
          ENV_REPO: ${{ github.repository }}
          ENV_ISSUE_ID: ${{ github.event.inputs.item_id }}
        shell: bash
        run: |
          # Set Title
          NewTitle="RefindPlus of Unknown Provenance: Exhibits Issues"
          echo "Updating issue #${ENV_ISSUE_ID} with title: ${NewTitle}"
          curl -f -X PATCH \
            -H "Authorization: token ${ENV_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${ENV_REPO}/issues/${ENV_ISSUE_ID} \
            -d "{\"title\": \"${NewTitle}\"}" || { echo "Title Update Failed"; exit 1; }
