name: PR Manager

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  handle-labels:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - if: github.actor == 'dakanji'
        id: add-labels-declined
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'Declined'

      - if: github.actor != 'refindplusrepo[bot]' && github.actor != 'dakanji'
        id: add-labels-withdrawn
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'Withdrawn'

      - id: remove-labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ steps.app-token.outputs.token }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'Triage,No-Log,Queries,Pending,Prorogued'
