
name: 'Manage Runs'

on:
  workflow_dispatch:
  # schedule = 01:01 on the 1st day of each month
  schedule:
    - cron: '1 1 1 * *'

jobs:

  # Prune Old Runs - https://github.com/Mattraks/delete-workflow-runs
  del_runs:
    name: Prune Runs
    runs-on: ubuntu-latest

    if: github.repository == 'RefindPlusRepo/RefindPlus'
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - id: prune-workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          retain_days: 61
          keep_minimum_runs: 0
